DB-10407 Add hdp3.1.5 platform
splicemachine/spliceengine pull request #4251
Opened 2020-10-08 15:07 UTC by bklo94

2020-10-13 18:59 UTC, msirek approved these changes
The changes look good.

2020-10-13 19:58 UTC, OlegMazurov requested changes
_HConfigurationTest_ unit test fails due to _guava_ version mismatch.
hadoop-common-3.1.1.3.1.5.124-1.jar requires

void checkArgument(boolean, java.lang.String, java.lang.Object);

which is available in guava-28.2-jre.jar, provided by HDP 3.1.5,  but not guava-12.0.1.jar, provided by Splice at test time.

2020-10-13 22:27 UTC, OlegMazurov requested changes
_HConfigurationTest_ unit test fails due to _guava_ version mismatch.
hadoop-common-3.1.1.3.1.5.124-1.jar requires

void checkArgument(boolean, java.lang.String, java.lang.Object);

which is available in guava-28.2-jre.jar, provided by HDP 3.1.5,  but not guava-12.0.1.jar, provided by Splice at test time.

2020-10-13 22:27 UTC, OlegMazurov commented on hbase_sql/pom.xml
> +        <dependency>
Redundant. Fix _org.apache.hive:hive-jdbc_

2020-10-13 22:27 UTC, OlegMazurov commented on splice_spark/pom.xml
> +        <dependency>
Redundant. Fix _org.apache.hive:hive-jdbc_ in _hbase_sql_.

2020-10-13 22:27 UTC, OlegMazurov commented on splice_spark2/pom.xml
> +        <dependency>
Redundant. Fix _org.apache.hive:hive-jdbc_ in _hbase_sql_.

2020-10-15 11:12 UTC, bklo94 commented
jenkins please test branch @hdp3.1.5

2020-10-15 11:37 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1706/

2020-10-15 16:25 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1710/

2020-10-15 17:56 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1712/

2020-10-15 23:57 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1713/

2020-10-16 15:09 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1720/

2020-10-16 15:49 UTC, bklo94 commented
jenkins please test branch @hdp3.1.5,skipTestsLongerThan2Minutes

2020-10-16 17:40 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1724/

2020-10-16 18:30 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1723/

2020-10-16 21:37 UTC, jyuanca commented
jenkins please test branch @hdp3.1.5

2020-10-17 01:49 UTC, OlegMazurov approved these changes

2020-10-17 03:48 UTC, spliceci commented
TEST SUCCEEDED +1

2020-10-22 03:28 UTC, carolp-503 approved these changes
+1

2020-10-27 10:28 UTC, merged