DB-10690 fix forgotten FirstWriteToken
splicemachine/spliceengine pull request #4577
Opened 2020-11-12 20:10 UTC by martinrupp

2020-11-12 20:11 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2020-11-12 20:13 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1933/

2020-11-12 20:25 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1934/

2020-11-12 21:53 UTC, dgomezferro requested changes
Very nice find @martinrupp !

I'd say the problem is only constrained to ForeignKey indices, because they have uniqueness to them but they don't have a constraint checker, so we run into the problem you described (always adding a first write token).

The proposed solution adds a lot of overhead for non-pk inserts, so I'd rather special case the FK indices by creating a dummy constraintChecker for them so that we always do conflict detection for them.

2020-11-12 22:20 UTC, martinrupp commented on splice_si_api/src/main/java/com/splicemachine/si/impl/server/SITransactor.java
> +                    possibleConflicts = table.getLatest(kvPair.getRowKey(), possibleConflicts);
note for myself: are these conflicts collected? why does getLatest have parameter possibleConfilcts?

2020-11-12 22:21 UTC, martinrupp commented
> Very nice find @martinrupp !
> 
> I'd say the problem is only constrained to ForeignKey indices, because they have uniqueness to them but they don't have a constraint checker, so we run into the problem you described (always adding a first write token).
> 
> The proposed solution adds a lot of overhead for non-pk inserts, so I'd rather special case the FK indices by creating a dummy constraintChecker for them so that we always do conflict detection for them.

i also had the feeling this adds overhead. The problem however is, that currently if we for some cases do not execute the line  `possibleConflicts = table.getLatest(kvPair.getRowKey(), possibleConflicts);`, then possibleConflicts is null, which is interpreted as "we need to write FIRST_WRITE_TOKEN or DELETE_RIGHT_AFTER_FIRST_WRITE_TOKEN", which will cause again duplicated FIRST_WRITE_TOKENS

2020-11-12 22:25 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/1937/

2020-11-13 14:38 UTC, dgomezferro approved these changes
Looks good! Please remove System.out calls, there are a few more than what I highlighted

2020-11-13 14:38 UTC, dgomezferro commented on hbase_storage/src/test/java/com/splicemachine/si/impl/server/SICompactionStateMutateTest.java
> +        System.out.println(toString(inputCells, false));
Remove

2020-11-13 14:38 UTC, dgomezferro commented on hbase_storage/src/test/java/com/splicemachine/si/impl/server/SICompactionStateMutateTest.java
> +        System.out.println(toString(outputCells, false));
Remove

2020-11-13 20:27 UTC, msirek approved these changes

2020-11-13 20:31 UTC, jyuanca approved these changes

2020-11-13 20:32 UTC, merged