DB-11141: return a warning if no rows are affected by a DML
splicemachine/spliceengine pull request #5048
Opened 2021-01-20 17:52 UTC by jyuanca

2021-01-20 17:53 UTC, jyuanca commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-01-20 18:22 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2292/

2021-01-20 21:35 UTC, msirek approved these changes

2021-01-20 22:34 UTC, jpanko1 approved these changes

2021-01-21 05:53 UTC, carolp-503 approved these changes
+1

2021-01-21 09:20 UTC, dgomezferro requested changes

2021-01-21 09:20 UTC, dgomezferro commented on splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SQLWarningIT.java
> +    public void TestNoRowsAffectedWarning() throws Exception {
can you add a negative test case with `splice.db2.error.compatible` set to false?

2021-01-21 09:20 UTC, dgomezferro commented on splice_machine/src/test/java/com/splicemachine/derby/impl/sql/execute/operations/SQLWarningIT.java
> +    public void TestNoRowsAffectedWarning() throws Exception {
method name should start with lowercase

2021-01-21 09:31 UTC, ascend1 commented
@jyuanca Can you please take a look at @dgomezferro 's comment?

2021-01-21 16:49 UTC, carolp-503 approved these changes
Additional changes look good to me.

2021-01-21 17:10 UTC, merged