DB-11307 grammar for MERGE INTO
splicemachine/spliceengine pull request #5110
Opened 2021-02-03 15:02 UTC by martinrupp

2021-02-11 03:33 UTC, msirek approved these changes

2021-03-02 10:48 UTC, dgomezferro approved these changes
Looks good!

2021-03-02 10:54 UTC, arnaud-splice requested changes

2021-03-02 10:54 UTC, arnaud-splice commented on db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/QueryTreeNodeVector.java
> +    final Class<T> eltClass; // needed for cast in #acceptChildren
What's the point of eltClass? The constructor that sets it does not seem to be used anywhere, and it looks kinda hacky.

2021-05-11 10:27 UTC, arnaud-splice approved these changes

2021-05-20 13:15 UTC, carolp-503 approved these changes
+1

2021-05-20 17:30 UTC, merged