Redo DB-10968 SET_GLOBAL_DATABASE_PROPERTY should check existence of properties, restrict execution of GET_REGION_SERVER_CONFIG_INFO
splicemachine/spliceengine pull request #5139
Opened 2021-02-09 14:01 UTC by martinrupp

2021-02-10 20:22 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-02-10 20:25 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2436/

2021-02-11 05:43 UTC, jyuanca approved these changes

2021-02-11 21:46 UTC, msirek approved these changes

2021-02-16 10:11 UTC, arnaud-splice requested changes

2021-02-16 10:11 UTC, arnaud-splice commented on db-engine/src/main/java/com/splicemachine/utils/DbEngineUtils.java
> +package com.splicemachine.utils;
License missing

2021-02-18 04:56 UTC, carolp-503 approved these changes
+1, but see Arnaud's comment about missing license file.

2021-02-18 14:57 UTC, martinrupp commented on db-engine/src/main/java/com/splicemachine/utils/DbEngineUtils.java
> +package com.splicemachine.utils;
done

2021-02-18 14:57 UTC, martinrupp commented on db-shared/src/main/java/com/splicemachine/db/iapi/reference/PropertyHelper.java
> +}
done

2021-02-18 14:57 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-02-18 15:27 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2471/

2021-02-18 16:27 UTC, arnaud-splice approved these changes

2021-02-20 05:51 UTC, merged