DB-11267 Fix sqlshell error selecting from sys.systriggers
splicemachine/spliceengine pull request #5153
Opened 2021-02-10 20:06 UTC by msirek

'select * from sys.systriggers' doesn't work in the packaged sqlshell.
Need to include the db-engine jar so it can deserialize ReferencedColumnsDescriptorImpl.

2021-02-10 20:08 UTC, msirek commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-02-10 23:30 UTC, spliceci commented
TEST SUCCEEDED +1

2021-02-11 09:04 UTC, martinrupp requested changes
Can you add a test to SqlshellIT.java for this?

2021-02-11 17:19 UTC, msirek commented
In today's standup we decided on fixing this in a different way, so I'm closing this PR.

2021-02-11 17:19 UTC, closed without merging