DB-11434 fix escaping table name in DESCRIBE (redux)
splicemachine/spliceengine pull request #5166
Opened 2021-02-12 12:12 UTC by hatyo

Fix issues discovered by @dyang-splice in QA of DB-10890.

2021-02-16 10:29 UTC, arnaud-splice approved these changes

2021-02-16 11:06 UTC, martinrupp requested changes
I had a look at the jira, and from there i tried CREATE and describe with `"tee%sss"` and `"TEMP  _TABLE"`, both work already now. can you describe what was not working before and what is now working. (maybe use template **description**, **how to test**)

2021-02-17 05:04 UTC, jyuanca approved these changes

2021-02-17 05:16 UTC, carolp-503 approved these changes
+1

2021-02-18 09:51 UTC, hatyo commented
> I had a look at the jira, and from there i tried CREATE and describe with `"tee%sss"` and `"TEMP _TABLE"`, both work already now. can you describe what was not working before and what is now working. (maybe use template **description**, **how to test**)

done, thanks.

2021-02-18 09:57 UTC, martinrupp approved these changes

2021-02-18 16:36 UTC, merged