DB-11345 Increase frequency sketch max map size for FK columns
splicemachine/spliceengine pull request #5179
Opened 2021-02-15 17:59 UTC by ascend1

2021-02-16 10:21 UTC, martinrupp commented
please provide some description what this does and how to test is. or is this just a rebase?

2021-02-16 12:57 UTC, ascend1 commented
jenkins please test branch @cdh6.3.0

2021-02-17 00:30 UTC, msirek commented on db-engine/src/main/java/com/splicemachine/db/iapi/stats/ColumnStatisticsImpl.java
> +        out.writeInt(frequenciesSketchMaxMapSize);
Is this the final version of the fix?  It doesn't look like the serialization issue is fixed yet.

2021-02-17 04:19 UTC, jyuanca requested changes
This PR contains many commits that are not relevant to DB-11345. Can you clean it up so that it is easier to review?

2021-02-17 15:42 UTC, closed without merging