DB-10258 Create parameter to disallow multidatabase creation
splicemachine/spliceengine pull request #5251
Opened 2021-03-04 09:02 UTC by arnaud-splice

## Short Description
This disables multidatabase as a default and introduces a new system procedure to enable it.

## Long Description
This introduces two new system procedures: 
```
SYSCS_UTIL.SYSCS_ENABLE_MULTIDATABASE()
SYSCS_UTIL.SYSCS_DISABLE_MULTIDATABASE()
```
Creating a new database is forbidden if multidatabase is disabled. Disabling multidatabase after the creation of a new database does not destroy that database, but only prevents the creation of new ones.
This parameter is persisted in zookeeper, because we need to be able to access during connection time.

 
## How to test
```
splice> show databases;
DATABASENAME
------------------------------------
SPLICEDB
splice> connect 'jdbc:splice://localhost:1527/splicedb3;user=foo;password=pass;create=true';
ERROR 42Y19: DERBY SQL error: SQLCODE: -1, SQLSTATE: 42Y19, SQLERRMC: Multidatabase is disabled
splice> call syscs_util.syscs_enable_multidatabase();
Statement executed.
ELAPSED TIME = 190 milliseconds
splice> connect 'jdbc:splice://localhost:1527/splicedb3;user=foo;password=pass;create=true';
ELAPSED TIME = 67 milliseconds
splice> show databases;
DATABASENAME
------------------------------------
SPLICEDB
SPLICEDB3
```

2021-03-09 11:59 UTC, martinrupp requested changes

2021-03-09 11:59 UTC, martinrupp commented on db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryOperatorNode.java
> +        //this.operandMatchIndexExprConglomDesc = conglomDesc;
can this be removed completely?

2021-03-09 17:58 UTC, arnaud-splice commented on db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/UnaryOperatorNode.java
> +        //this.operandMatchIndexExprConglomDesc = conglomDesc;
Done

2021-03-09 19:16 UTC, martinrupp approved these changes

2021-03-10 00:59 UTC, jyuanca approved these changes

2021-03-10 05:05 UTC, carolp-503 approved these changes
+1

2021-03-10 13:29 UTC, merged