DB-11701 Update to set false mirror state zookeeper properties
splicemachine/spliceengine pull request #5361
Opened 2021-03-31 15:25 UTC by bklo94

## Short Description
Update documentation for cdh and for hdp. Also update the hdp scripts to add the new properties

## Long Description
Add these two settings which should allow for faster restarts for a large cluster that is running on HBase 2.0+

## How to test
N/A

2021-03-31 17:55 UTC, jyuanca approved these changes

2021-04-06 08:56 UTC, arnaud-splice approved these changes

2021-04-06 09:01 UTC, dgomezferro requested changes
Marking as changes requested to discuss how to address this issue, even though I'm +1 on merging:
`hbase.migrate.table.state.from.zookeeper` should be True when migrating from HBase 1.X to 2.X, so our upgrade procedure should make sure that's the case. After that first migration we should set it to false. Where should we make sure of that?

2021-04-08 20:22 UTC, carolp-503 approved these changes
+1

2021-04-08 20:59 UTC, merged