DB-11818: fix table/schema backup stats backward compatibility
splicemachine/spliceengine pull request #5374
Opened 2021-04-06 01:17 UTC by jyuanca

## Short Description
On a post-2003 build, restoring a backup from pre-2003 build failed

## Long Description
Build 2003 changes serialization of statistics. However, older backup still stores statistics in old serialization format. To fix this issue, bump up backup version number. For pre-2009 backup, its stats will be read using old format first. If that does not work, read using newer format. For post-2009 backup, its stats will be always stored and read using new format.

## How to test
Make table/schema backup on a pre-2003 build. Table/schema and their stats should be restored successfully.

2021-04-06 03:20 UTC, jyuanca commented
Please also review ee branch

2021-04-06 03:21 UTC, jyuanca commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-06 05:59 UTC, spliceci commented
TEST SUCCEEDED +1

2021-04-06 09:01 UTC, ascend1 approved these changes

2021-04-06 09:24 UTC, ipraznik-splice requested changes

2021-04-06 09:24 UTC, ipraznik-splice commented on db-engine/src/main/java/com/splicemachine/db/iapi/services/io/DataInputUtil.java
> +    public static void setReadOldFormat(Boolean b) {
I cannot find, how methods setReadOldFormat, clearReadOldFormat are used. Are they needed?

2021-04-06 09:26 UTC, ipraznik-splice commented on db-engine/src/main/java/com/splicemachine/db/iapi/services/io/DataInputUtil.java
> +    public static void setReadOldFormat(Boolean b) {
Found in EE :)

2021-04-06 09:27 UTC, ipraznik-splice approved these changes

2021-04-06 09:30 UTC, arnaud-splice approved these changes

2021-04-07 04:41 UTC, carolp-503 approved these changes
+1

2021-04-07 15:21 UTC, merged