DB-9686 Introduce new auto analyze mechanism
splicemachine/spliceengine pull request #5394
Opened 2021-04-15 15:06 UTC by arnaud-splice

## Short Description

Introduce a new auto analyze mechanism that kicks off analyze once a table has received a certain number of updates/deletes/inserts

## Long Description

This introduces a new column in SYS.SYSTABLES: `AUTO_ANALYZE`
This can be set per table or per schema via:
```
call syscs_util.set_auto_analyze('s', 't', 20)
```

Each region server maintains a count of modified rows. Once that count exceeds the auto_analyze value set in systables, an external connection is opened to trigger analyze on that table.
For now, this will only succeed if the user who ran the insertion has analyze privilege. 

## How to test

2021-04-15 20:57 UTC, arnaud-splice commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-15 21:05 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2770/

2021-04-15 23:16 UTC, arnaud-splice commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-15 23:53 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2771/

2021-04-16 13:36 UTC, arnaud-splice commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-16 16:53 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2774/

2021-04-20 09:24 UTC, hatyo requested changes

2021-04-20 09:24 UTC, hatyo commented on splice_machine/src/main/java/com/splicemachine/derby/impl/sql/catalog/DD_stats.java
> +public class DD_stats {
Name is not inline with our naming conventions

2021-04-20 09:24 UTC, hatyo commented on splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/DMLWriteOperation.java
> +        Thread thread = new Thread(new AnalyzeRunnable(RemoteUser.user.get()));
Please name the thread, it makes easier to debug

2021-04-20 09:24 UTC, hatyo commented on splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/InsertOperation.java
> +            DataSet<ExecRow> written = writer.write();
please revert

2021-04-20 09:24 UTC, hatyo commented on splice_machine/src/main/java/com/splicemachine/derby/impl/sql/execute/operations/DMLWriteOperation.java
> +                try (Connection connection = RemoteUser.getConnection("Arnauds-MacBook-Pro.local:1528");
I think this is incorrect, please remove/refactor.

2021-04-27 09:17 UTC, closed without merging