DB-11533 Introduce parameter to change return type of count
splicemachine/spliceengine pull request #5402
Opened 2021-04-19 13:42 UTC by arnaud-splice

## Description

This introduces a new parameter `splice.bind.countReturnType` to toggle the return type of COUNT from big int to int.

## How to test

```
select typeof(count(*)) from sysibm.sysdummy1;
1
----------------------------------------
BIGINT

call syscs_util.syscs_set_global_database_property('splice.bind.countReturnType', 'integer');
select typeof(count(*)) from sysibm.sysdummy1;
1
----------------------------------------
INTEGER

call syscs_util.syscs_set_global_database_property('splice.bind.countReturnType', 'bigint');
select typeof(count(*)) from sysibm.sysdummy1;
1
----------------------------------------
BIGINT

2021-04-20 05:30 UTC, jyuanca approved these changes

2021-04-20 08:53 UTC, ipraznik-splice approved these changes

2021-04-20 08:57 UTC, dgomezferro approved these changes

2021-04-20 08:57 UTC, dgomezferro commented on db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/SPSPropertyCountReturnType.java
> + * An SPS property that governs timestamp field(s) in a query.
Update comment

2021-04-20 09:03 UTC, arnaud-splice commented on db-engine/src/main/java/com/splicemachine/db/impl/sql/execute/SPSPropertyCountReturnType.java
> + * An SPS property that governs timestamp field(s) in a query.
Done

2021-04-20 15:40 UTC, OlegMazurov commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-20 19:00 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2782/

2021-04-21 21:54 UTC, OlegMazurov requested changes
Please fix the newly added GlobalDatabasePropertyIT

2021-04-21 23:56 UTC, arnaud-splice commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-22 00:30 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2791/

2021-04-22 15:16 UTC, arnaud-splice commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-22 18:22 UTC, spliceci commented
TEST SUCCEEDED +1

2021-04-22 20:39 UTC, arnaud-splice commented
> Please fix the newly added GlobalDatabasePropertyIT

done

2021-04-29 00:05 UTC, merged