DB-11539/DB-11784 EXPORT fixes
splicemachine/spliceengine pull request #5409
Opened 2021-04-21 21:51 UTC by martinrupp

## Short Description
This changes does
- DB-11784: Add feature that IMPORT_DATA can now read from parquet
- DB-11539: fix EXPORT so that EXPORT uses DEFAULT_TIMESTAMP_FORMAT if timestamp_format is not set

## Long Description
- DB-11784: We can already EXPORT to parquet, now we can also IMPORT. Since we can import from a directory, we will use PARQUET import once we have one `.parquet` file in the directory. If we have .orc, we use orc. Otherwise, we use .csv .
- DB-11539: Before this, a change in global database property `splice.function.timestampFormat` would change the behavior of EXPORT when not timestamp_format was given and the "default" value should be taken.  Since only the EXPORT would use that default value, but not IMPORT, we had a mismatch between these two, so we aligned now both so that default EXPORT can be read by default EXPORT.
- Furthermore, this changes does some refactoring and improves the Export test to test that all EXPORTd files can be IMPORTd with the same settings.

## How to test DB-11784 IMPORT_DATA parquet

```
EXPORT TO '/tmp/parquet_test' AS PARQUET  VALUES (1, 'a'), (2, 'b'), (3, 'c');
call SYSCS_UTIL.IMPORT_DATA('SPLICE', 'PARQUET_TEST', null,
       '/tmp/parquet_test/', null, null, null, null, null, '0', '/tmp', false, null);
CREATE TABLE PARQUET_TEST ( I INTEGER, C VARCHAR(32));
SELECT * FROM PARQUET_TEST;
```
should result in
```
I          |C                               
--------------------------------------------
1          |a                               
2          |b                               
3          |c       
```

## How to test DB-11539 EXPORT should use DEFAULT_TIMESTAMP_FORMAT
The following code should run independent of setting of
`call syscs_util.syscs_set_global_database_property('splice.function.timestampFormat', X)`, where X can be `null`, `'true'` or `'false'`.

```
CREATE TABLE A ( T TIMESTAMP);
INSERT INTO A VALUES ('2020-01-01 12:15:16.123456789');
EXPORT TO '/tmp/timestamp_test' AS CSV SELECT * FROM A;

DELETE FROM A; -- reset table A
call SYSCS_UTIL.IMPORT_DATA('SPLICE', 'A', null, '/tmp/timestamp_test/', null,
     null, null, null, null, '0', '/tmp', false, null);
SELECT * FROM A;
-- 2020-01-01 12:15:16.123456   
```

2021-04-22 09:43 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-22 09:45 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2796/

2021-04-22 09:47 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2799/

2021-04-22 09:47 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-22 09:48 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2800/

2021-04-22 10:13 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-22 10:14 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2801/

2021-04-22 10:44 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-22 10:47 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2802/

2021-04-23 13:54 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-23 14:46 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2815/

2021-04-27 11:09 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-27 11:38 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2830/

2021-04-28 00:42 UTC, jyuanca approved these changes

2021-04-28 18:37 UTC, arnaud-splice requested changes
There are a couple of TODOs in ExportOperationIT that we should address before merging this PR. They effectively remove some test coverage for the old export syntax.

2021-04-29 08:35 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-29 08:45 UTC, arnaud-splice approved these changes

2021-04-29 09:09 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2841/

2021-04-29 13:06 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-29 13:38 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2846/

2021-04-29 15:20 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-29 18:29 UTC, spliceci commented
TEST SUCCEEDED +1

2021-04-29 22:11 UTC, carolp-503 reviewed
+1

2021-04-29 22:40 UTC, merged