DB-11903 Materialize updates into all values
splicemachine/spliceengine pull request #5412
Opened 2021-04-22 14:59 UTC by dgomezferro

## Short Description
Merge existing data with update to materialize all values into the beginning of the MVCC history for each row.

## Long Description
Currently we only write what has changed in each update, but in some cases this causes performance degradation, for instance when updating repeatedly a single column we end up generating a large MVCC history that we have to scan over when we want to reconstruct the full row.

This change materializes the full row for each update, so that we always have the latest values at the beginning of the MVCC history.

Caveats:
- During WW conflict if the latest value is rolledback we don't perform the materialization
- This adds some overhead (both CPU / Memory and storage)

## How to test
Repeated updates to a single column shouldn't deteriorate full row scans performance anymore.

2021-04-22 14:59 UTC, dgomezferro commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-04-22 17:53 UTC, spliceci commented
TEST SUCCEEDED +1

2021-04-27 02:41 UTC, msirek approved these changes

2021-04-27 10:09 UTC, hatyo approved these changes
Nice work, I really like the tests you added, thanks for that!

2021-04-27 10:17 UTC, arnaud-splice requested changes
+1 once Youssef comments were addressed

2021-04-29 04:19 UTC, carolp-503 approved these changes
+1

2021-04-30 08:12 UTC, dgomezferro commented on splice_access_api/src/main/java/com/splicemachine/storage/util/UpdateUtils.java
> +        BitSet result = new BitSet(bitSet.capacity()/2);
If I understand it correctly it expects the maximum index/value to be set on the BitSet, not the maximum number of set bits.

For instance:
```
BitSet s = new BitSet(64);
s.capacity(); // 64
s.set(100); // 100 > 64, needs to resize
s.capacity(); // 320
```

2021-04-30 08:19 UTC, dgomezferro commented on splice_access_api/src/main/java/com/splicemachine/storage/util/UpdateUtils.java
> +    public static BitSet halveSet(BitSet bitSet) {
Yes, I should have documented this, but this method expects the BitSet to be the concatenation of two copies of an original BitSet, so in your case input should be something like `[0,0,1,0,1,0,0,1,0,1]`:
```
BitSet bitSet = new BitSet(10); // bitSet=[0,0,0,0,0,0,0,0,0,0]
bitSet.set(3);
bitSet.set(5);
bitSet.set(8);
bitSet.set(10);                 // bitSet=[0,0,1,0,1,0,0,1,0,1]
BitSet half = halveSet(bitSet); // half=  [0,0,1,0,1]
System.out.println(half); // result is: {3,5}
```
I'll improve the documentation here, thanks!

2021-05-04 09:36 UTC, hatyo commented on splice_access_api/src/main/java/com/splicemachine/storage/util/UpdateUtils.java
> +        BitSet result = new BitSet(bitSet.capacity()/2);
You're right, I was confused about it, thanks for checking it and correcting my understanding.

2021-05-04 09:53 UTC, arnaud-splice approved these changes

2021-06-16 21:31 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-06-17 01:42 UTC, cloudspliceci commented
TEST SUCCEEDED +1

2021-06-17 07:30 UTC, merged