[QA-2863] Basic set of microbenchmarks
splicemachine/spliceengine pull request #5436
Opened 2021-04-30 15:03 UTC by qvad

## Short Description
Set of simple microbenchmarks

## Long Description
Idea is to cover simple execution pieces by microbenchmarks. Initial set covers insert, delete and update operations.
Here we a retrying to check how these basic operation depends of number of indexes (and columns in indexes), number of columns.

OLAP benchmarks are disabled for now, because insert performance is not so good right now.
Main idea is to run it against Cloud environments.

Possible improvements:
1. Not sure how long these tests should be evaluated (maybe we need to tune params)
2. Enable OLAP execution for some cases
3. Improve logic of benchmarks

## How to test
NA

2021-04-30 15:43 UTC, OlegMazurov commented on splice_machine/src/test/java/com/splicemachine/benchmark/execution/DeleteBenchmark.java
> +                    curSize.set(0);
I'd move _curSize_ to _ExecutionBenchmark_.
To initialize it, you may need to introduce
`protected void populateTables(SpliceSchemaWatcher spliceSchemaWatcher, int size, int batchSize, int numTableColumns, String insertParamStr, int concurrency)`
Make the current _populateTables_:
`private void populateTables(SpliceSchemaWatcher spliceSchemaWatcher, int size, int batchSize, int numTableColumns, String insertParamStr)`
Use _concurrency_ to either invoke it sequentially or via runBenchmark().

2021-05-04 09:58 UTC, martinrupp requested changes

2021-05-04 09:58 UTC, martinrupp commented on splice_machine/src/test/java/com/splicemachine/benchmark/execution/DeleteBenchmark.java
> +
```
    @Rule
    public SpliceWatcher methodWatcher = new SpliceWatcher(SCHEMA);
```

2021-05-04 09:58 UTC, martinrupp commented on splice_machine/src/test/java/com/splicemachine/benchmark/execution/DeleteBenchmark.java
> +        testStatement.execute("CREATE TABLE " + BASE_TABLE + tableDefStr);
`methodWatcher.execute("CREATE TABLE " + BASE_TABLE + tableDefStr);`

2021-05-04 09:58 UTC, martinrupp commented on splice_machine/src/test/java/com/splicemachine/benchmark/execution/DeleteBenchmark.java
> +        testStatement.execute(String.format("call syscs_util.syscs_flush_table('%s', '%s')", SCHEMA, BASE_TABLE));
methodWatcher.execute

2021-05-04 09:58 UTC, martinrupp commented on splice_machine/src/test/java/com/splicemachine/benchmark/execution/DeleteBenchmark.java
> +        try (ResultSet rs = testStatement.executeQuery("ANALYZE SCHEMA " + SCHEMA)) {
methodWatcher.executeQuery

2021-05-04 09:58 UTC, martinrupp commented on splice_machine/src/test/java/com/splicemachine/benchmark/execution/DeleteBenchmark.java
> +        testConnection.close();
remove

2021-05-04 09:58 UTC, martinrupp commented on splice_machine/src/test/java/com/splicemachine/benchmark/execution/DeleteBenchmark.java
> +                    testStatement.execute("call SYSCS_UTIL.VACUUM()");
methodWatcher

2021-05-04 09:58 UTC, martinrupp commented on splice_machine/src/test/java/com/splicemachine/benchmark/execution/DeleteBenchmark.java
> +            try (PreparedStatement query = conn.prepareStatement(sqlText)) {
try (PreparedStatement query = methodWatcher.prepareStatement(sqlText)) {
                for (int i = 0; i < ExecutionBenchmark.NUM_EXECS; ++i) {

2021-05-04 09:58 UTC, martinrupp commented on splice_machine/src/test/java/com/splicemachine/benchmark/execution/ExecutionBenchmark.java
> +        return connection;
remove

2021-05-04 09:58 UTC, martinrupp commented on splice_machine/src/test/java/com/splicemachine/benchmark/execution/ExecutionBenchmark.java
> +    protected void populateTables(SpliceSchemaWatcher spliceSchemaWatcher, int size, AtomicInteger curSize, int batchSize, int numTableColumns, String insertParamStr) {
use methodWatcher

2021-05-04 09:58 UTC, martinrupp commented on splice_machine/src/test/java/com/splicemachine/benchmark/execution/ExecutionBenchmark.java
> +    protected Statement testStatement;
remove this, use methodWatcher instead.

2021-05-04 09:58 UTC, martinrupp commented on splice_machine/src/test/java/com/splicemachine/benchmark/execution/DeleteBenchmark.java
> +        testConnection = makeConnection(spliceSchemaWatcher, false);
`methodWatcher.setConnection( methodWatcher.connectionBuilder().useOLAP(false).schema(SCHEMA).build() );`

2021-06-01 11:26 UTC, martinrupp approved these changes

2021-06-01 17:35 UTC, OlegMazurov approved these changes

2021-06-01 17:35 UTC, OlegMazurov commented on splice_machine/src/test/java/com/splicemachine/benchmark/execution/InsertBenchmark.java
> +            for (int i = 0; i < ExecutionBenchmark.NUM_WARMUP_RUNS; ++i) {
It would seem logical to use _NUM_WARMUP_RUNS_ when _warmup_ == _true_ and _NUM_EXECS_ otherwise.

2021-06-01 17:35 UTC, OlegMazurov commented on splice_machine/src/test/java/com/splicemachine/benchmark/execution/DeleteBenchmark.java
> +                testStatement.executeUpdate("call SYSCS_UTIL.VACUUM()");
_execute()_ is more appropriate here than _executeUpdate()_

2021-06-01 19:56 UTC, carolp-503 approved these changes
+1

2021-06-02 12:20 UTC, merged