DB-11960 Check constant in-list condition in predicates
splicemachine/spliceengine pull request #5462
Opened 2021-05-11 17:27 UTC by arnaud-splice

## Short Description
(e.g. short description of the PR)

## Long Description
(e.g. why in detail, how, potential further work)

## How to test
(e.g. if bugfix: how to reproduce bug / impact)
(if feature: a easy example of how to check the feature)
(if feature is a configuration: an example to see different behavior with different configuration)

2021-05-11 17:27 UTC, arnaud-splice commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-05-11 22:43 UTC, spliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2900/

2021-05-12 14:56 UTC, arnaud-splice commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-05-12 18:52 UTC, spliceci commented
TEST SUCCEEDED +1

2021-05-18 09:12 UTC, martinrupp approved these changes

2021-05-18 09:53 UTC, hatyo commented on db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/InListOperatorNode.java
> +            return this;
I think we can return `false` here, right?
i.e.
`return (ValueNode) getNodeFactory().getNode(C_NodeTypes.BOOLEAN_CONSTANT_NODE, false, getContextManager());`

2021-05-18 09:55 UTC, hatyo requested changes
If the LHS is `null` I am guessing you can also return `false` immediately, e.g. `null in (1,2,3) => false`. Could you please check this case?

2021-05-18 11:34 UTC, arnaud-splice commented
> If the LHS is `null` I am guessing you can also return `false` immediately, e.g. `null in (1,2,3) => false`. Could you please check this case?

That is not the case. 
If this is the top node of a predicate, then `null in (1,2,3)` will indeed evaluate to false, because a null predicate is a false predicate.
However, if not the top node of a predicate, `null in (1,2,3)` should evaluate to null.
We could return null directly here, but it leads to complications that are addressed by [DB-12077](https://github.com/splicemachine/spliceengine/pull/5474)

2021-05-18 11:46 UTC, hatyo approved these changes

2021-05-20 01:51 UTC, carolp-503 approved these changes
+1

2021-05-20 15:34 UTC, merged