[DRAFT] DB-10961 Get rid of the NodeFactory part 2
splicemachine/spliceengine pull request #5483
Opened 2021-05-18 12:42 UTC by martinrupp

iterative PR to get rid of NodeFactory / getNode

2021-05-18 14:41 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0

2021-05-18 19:44 UTC, spliceci commented
TEST SUCCEEDED +1

2021-05-25 18:16 UTC, martinrupp commented
note this is best reviewed commit by commit. it's just adding constructors and replacing `getNodeFactory().getNode(X, ...)` with `new X(...)` .

2021-05-27 17:03 UTC, arnaud-splice requested changes
Great change! One minor request for changes.

2021-05-28 10:14 UTC, dgomezferro approved these changes
Nice simplification! +1 conditioned on the sysout removal

2021-05-28 11:37 UTC, martinrupp commented on db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/ResultColumn.java
> +            System.out.println("ha");
thanks done

2021-05-31 08:17 UTC, arnaud-splice approved these changes

2021-06-03 00:58 UTC, carolp-503 approved these changes
+1

2021-06-04 22:16 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-06-05 02:28 UTC, cloudspliceci commented
TEST SUCCEEDED +1

2021-06-07 07:07 UTC, merged