[DRAFT] DB-10961 Get rid of the NodeFactory part
splicemachine/spliceengine pull request #5501
Opened 2021-05-25 09:53 UTC by martinrupp

(DO NOT REVIEW, MIGHT BE FORCE-PUSHED)

2021-06-08 07:22 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0

2021-06-15 08:49 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0

2021-06-15 15:40 UTC, cloudspliceci commented
TEST SUCCEEDED +1

2021-06-17 08:02 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0

2021-06-17 14:42 UTC, cloudspliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3160/

2021-06-20 20:27 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-06-21 00:30 UTC, cloudspliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3190/

2021-06-21 07:17 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-06-21 11:21 UTC, cloudspliceci commented
TEST SUCCEEDED +1

2021-06-22 09:23 UTC, dgomezferro requested changes
Change looks good, I only have a comment regarding the `.equals()` implementation.

2021-06-22 09:26 UTC, martinrupp commented on db-engine/src/main/java/com/splicemachine/db/impl/sql/compile/AllResultColumn.java
> +    }
yeah this is weird... SpotBugs complaint about missing equals function, but i don't think we need this. will remove again

2021-06-22 10:53 UTC, dgomezferro approved these changes
Thanks for the changes Martin, looks good to me!

2021-06-22 12:31 UTC, martinrupp commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-06-22 19:32 UTC, cloudspliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3206/

2021-06-22 21:22 UTC, jyuanca approved these changes

2021-06-23 01:03 UTC, cloudspliceci commented
TEST SUCCEEDED +1

2021-06-29 06:13 UTC, carolp-503 approved these changes
+1

2021-06-29 08:53 UTC, merged