DB-DB-12130: quote schema and table names for check_table
splicemachine/spliceengine pull request #5515
Opened 2021-05-27 00:35 UTC by jyuanca

## Short Description
System procedure syscs_util.check_table has problem with quoted schema or table name.

## Long Description
System procedure syscs_util.check_table has problem with quoted schema or table name. This was caused by a query that does not quote schema and table name.

## How to test
Run this test case
create table "t"(i int);
insert into "t" values 1,2,3;
create index ti on "t"(i);
call syscs_util.check_table('SPLICE', null, null, 1, '/path/to/report');

2021-05-27 00:37 UTC, jyuanca commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-05-27 03:26 UTC, jyuanca commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-05-27 04:19 UTC, cloudspliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/2967/

2021-05-27 06:48 UTC, cloudspliceci commented
TEST SUCCEEDED +1

2021-06-01 09:00 UTC, arnaud-splice requested changes

2021-06-01 09:00 UTC, arnaud-splice commented on splice_machine/src/main/java/com/splicemachine/derby/procedures/SpliceTableAdmin.java
> +                "select count(*) from \"%s\".\"%s\" --splice-properties index=%s", schema, table, index==null?"null":index);
Please use `IdUtil.mkQualifiedName` instead

2021-06-01 09:21 UTC, martinrupp approved these changes

2021-06-02 00:15 UTC, jyuanca commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-06-03 02:25 UTC, msirek approved these changes

2021-06-03 09:27 UTC, dgomezferro approved these changes

2021-06-03 17:05 UTC, carolp-503 approved these changes
+1

2021-06-03 17:32 UTC, merged