DB-11110 introduce SHOW CREATE VIEW
splicemachine/spliceengine pull request #5588
Opened 2021-06-17 12:35 UTC by hatyo

##  Description
In this PR a new `show create view` sqlshell command is introduced that shows, for a given view, its DDL statement, similar to what `show create table` does for a given table name.

## How to test
Here are some examples:

```sql
create table t1(col1 int);
create view v1 as select * from t1;
show create view v1;
DDL
---
create view v1 as select * from t1;

create view v2 as select * from v1;
show create view v2;
DDL
---
create view v2 as select * from v1;
```

2021-06-21 22:00 UTC, jyuanca requested changes

2021-06-21 22:00 UTC, jyuanca commented on splice_machine/src/main/java/com/splicemachine/derby/procedures/ShowCreateViewProcedure.java
> +    public static List<String> SHOW_CREATE_VIEW_CORE(String schemaName, String viewName) throws SQLException {
If this procedure always returns one string, change the return type from List<String> to String

2021-06-22 09:05 UTC, ipraznik-splice approved these changes

2021-06-23 10:23 UTC, arnaud-splice commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-06-23 13:48 UTC, cloudspliceci commented
TEST SUCCEEDED +1

2021-06-23 15:03 UTC, jyuanca approved these changes

2021-06-23 18:08 UTC, bklo94 commented
jenkins please test branch @mem

2021-06-23 19:06 UTC, cloudspliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3220/

2021-06-23 19:18 UTC, carolp-503 approved these changes
+1

2021-06-24 12:55 UTC, arnaud-splice commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-06-24 17:13 UTC, cloudspliceci commented
TEST FAILED
http://nexus.splicemachine.com:8080/job/spliceengine-PR/job/Splice-PR-Branch/3230/

2021-06-29 08:45 UTC, arnaud-splice commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-06-29 13:10 UTC, cloudspliceci commented
TEST SUCCEEDED +1

2021-07-06 15:25 UTC, merged