DB-12222 Track all active sessions
splicemachine/spliceengine pull request #5624
Opened 2021-06-28 12:17 UTC by ascend1

## Short Description
This PR implements a new admin system procedure `syscs_util.syscs_get_active_sessions()`, which lists all active sessions on all region servers.

## Long Description
This is the first step of cleaning up obsolete local temporary tables.

Each region server has a singleton instance of `SessionsWatcherImpl`. Internally, it maintains a concurrent hash set recording active sessions on this region server. Each session registers itself in setting up the connection and unregisters itself when disconnected from the region server.

When calling `syscs_util.syscs_get_active_sessions()` on a region server, `SessionWatcherImpl.getAllActiveSessions()` sends a request via protobuf to all region servers and merge returned active sessions from all region servers into a single list.

On mem platform, there is no region server communication and session IDs are tracked using a single instance of `MSessionsWatcherImpl`.

The IT is currently marked as ignored because currently, we do not have a dedicate session ID field in a connection. At the moment we always use `lcc.getInstanceNumber()`, which is unique only to a region server. For this reason, multiple connections on different region servers could have the same session ID, making the test sporadic. This issue is tracked in DB-12283.

## How to test
Run `syscs_util.syscs_get_active_sessions()` from a connection with admin privileges returns a list of all active session IDs. This list should contain all connections on all region servers, despite of from which session on which region server this statement is executed.

2021-06-28 12:22 UTC, ascend1 commented
jenkins please test branch @cdh6.3.0,skipTestsLongerThan2Minutes

2021-06-28 16:32 UTC, cloudspliceci commented
TEST SUCCEEDED +1

2021-06-29 09:10 UTC, ipraznik-splice approved these changes

2021-06-29 09:16 UTC, arnaud-splice approved these changes

2021-06-29 09:25 UTC, arnaud-splice requested changes
As discussed during the review session, killing the client does not seem to remove the session id from the list of active sessions.

2021-06-29 10:11 UTC, arnaud-splice approved these changes
Turns out that it is properly cleaned up after all

2021-06-29 18:22 UTC, jyuanca approved these changes

2021-06-30 22:23 UTC, carolp-503 approved these changes
+1

2021-06-30 22:35 UTC, merged

2021-06-30 22:37 UTC, ascend1 commented on db-engine/src/main/java/com/splicemachine/db/impl/jdbc/EmbedConnection.java
> +                }
That makes sense. I'll add it in the following PR.